### ISSUE TITLE
[Suggestion] Update modules and enable build for all arches

### ISSUE THREAD

**Issue by A6GibKm** [flathub/org.dash.electrum.electrum_dash#3]
I added all the python3 modules required for a `[full]` install at https://github.com/flathub/org.electrum.electrum/pull/13, that also allowed for builds in arches other than x86_64. There might be something you find useful there. Note that older versions require `qdarkstyle<2.8` and this PR features version 2.8.1.

**Comment by zebra-lucky** [comment]
Thanks!

Currently fork is based on 3.3.8 version of electrum,
but I'll look to changes. Will try to do multiarch build.

**Comment by A6GibKm** [comment]
There are many incompatibilities based on the [requirements](https://github.com/spesmilo/electrum/tree/e81f4bdcd11a072e7c4f38fb1c7eec19c2f7e1a8/contrib/requirements). Note that the only thing that was incompatible with multi-arch was the PyQt5 module, since it downloaded 2 sources for x86_64. 

On the other hand `flatpak-pip-genertator` is able to make the manifests for requirememnts.txt and requirements-hw.txt, you just have to add `setup-tools, pip, wheel` when necesary and the `hidapi` module requires an `env` like in the PR mentioned.

**Comment by zebra-lucky** [comment]
Reviewed chages, thanks!

Need to read more about `flatpak-pip-genertator`.

Dash Electrum need additional two builds to support other architectures.
`x11-hash`, and `python-bls` (which is Cython and libgmp based).
I'll to try to redo builds for the next release.

**Comment by A6GibKm** [comment]
See https://github.com/flatpak/flatpak-builder-tools/tree/master/pip. Look at how the pyqt5 modules are being build. `x11-hash` is multi-arch and `python-bls` ships a `.tar.gz` that might be used.

**Comment by zebra-lucky** [comment]
Looking into supported architectures. Seems it will be no problems.
`x11-hash`, `python-bls` already run in Android builds for `armeabi-v7a`, `arm64-v8a`,
and i386 is used in PPA builds.

**Comment by zebra-lucky** [comment]
@A6GibKm, thank you for advices!
Today in PR #4 added changes to modules with `flatpak-pip-genertator`,
and all was build on multiple architectures.
